---
REFERENCE: hg38_canonical
SEX_POP: sex_info
SPLIT_DIR: index
WND_WIDTH: 500
GC_WIDTH: 200

REF_FILES:
    hg19:
        MASK_TRACK: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/HG19-noWM-pad36
        SUNK_MASK_TRACK: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/hg19_sunk_depth_mask.dts
        CONTIGS: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/hg19_contigs.txt
        GC_TRACK: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/hg19-gc-w200.GC_content
        WNDS_PKL: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/500_bp_windows.pkl
        SUNK_WNDS_PKL: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/500_bp_windows.sunks.pkl
        CONTROL_LOCATIONS: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/control_location_hg19
        GENOME: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/hg19.fa
        DGV_ANNOTATIONS: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/DGV_variation_hg19.annotation.DTS
        GENOMIC_SUPER_DUP_ANNOTATIONS: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/genomicSuperDups_hg19.annotation.DTS
        GAP_ANNOTATIONS: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/genomic_gaps_hg19.annotation.DTS
    hg19_canonical:
        MASK_TRACK: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/HG19-noWM-pad36.no_random
        SUNK_MASK_TRACK: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/hg19_sunk_depth_mask.dts
        CONTIGS: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/hg19_masked.fai
        GC_TRACK: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/hg19-gc-w200.GC_content
        WNDS_PKL: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/500_bp_windows.pkl
        SUNK_WNDS_PKL: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/500_bp_windows.sunks.pkl
        CONTROL_LOCATIONS: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/control_location_hg19
        GENOME: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/hg19.fa
        DGV_ANNOTATIONS: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/DGV_variation_hg19.annotation.DTS
        GENOMIC_SUPER_DUP_ANNOTATIONS: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/genomicSuperDups_hg19.annotation.DTS
        GAP_ANNOTATIONS: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/genomic_gaps_hg19.annotation.DTS

    hg38:
        MASK_TRACK: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/hg38_noWM_pad36
        SUNK_MASK_TRACK: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/hg38_sunk_mask_track_pad36_e0.dts
        CONTIGS: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/hg38.rmsk_and_trf.canonical.fa.fai
        GC_TRACK: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/hg38_gc_w200.GC_content
        WNDS_PKL: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/500_bp_windows.pkl
        SUNK_WNDS_PKL: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/500_bp_windows.sunks.pkl
        CONTROL_LOCATIONS: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/control_location_hg38
        GENOME: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/hg38.rmsk_and_trf.canonical.fa
        DGV_ANNOTATIONS: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/DGV_variation_hg38.annotation.DTS
        GENOMIC_SUPER_DUP_ANNOTATIONS: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/genomicSuperDups_hg38.annotation.DTS
        GAP_ANNOTATIONS: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/genomic_gaps_hg38.annotation.DTS
    hg38_canonical:
        MASK_TRACK: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/hg38_noWM_pad36
        SUNK_MASK_TRACK: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/hg38_sunk_mask_track_pad36_e0.dts
        CONTIGS: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/hg38.rmsk_and_trf.canonical.fa.fai
        GC_TRACK: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/hg38_gc_w200.GC_content
        WNDS_PKL: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/500_bp_windows.pkl
        SUNK_WNDS_PKL: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/500_bp_windows.sunks.pkl
        CONTROL_LOCATIONS: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/control_location_hg38
        GENOME: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/hg38.rmsk_and_trf.canonical.fa
        DGV_ANNOTATIONS: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/DGV_variation_hg38.annotation.DTS
        GENOMIC_SUPER_DUP_ANNOTATIONS: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/genomicSuperDups_hg38.annotation.DTS
        GAP_ANNOTATIONS: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/genomic_gaps_hg38.annotation.DTS
    hg38_noM:
        MASK_TRACK: /net/eichler/vol2/eee_shared/assemblies/hg38/read_depth/illumina/hg38_noWM_pad36
        SUNK_MASK_TRACK: /net/eichler/vol2/eee_shared/assemblies/hg38/read_depth/illumina/hg38_sunk_mask_track_pad36_e0.dts
        CONTIGS: /net/eichler/vol2/eee_shared/assemblies/hg38/indexes/hg38_noM/mrsfastULTRA/hg38.rmsk_and_trf.canonical.fa.fai
        GC_TRACK: /net/eichler/vol2/eee_shared/assemblies/hg38/indexes/hg38_noM/read_depth/illumina/hg38_gc_w200.GC_content
        WNDS_PKL: /net/eichler/vol2/eee_shared/assemblies/hg38/indexes/hg38_noM/DTS_windows/hg38_slide/500_bp_windows.pkl
        SUNK_WNDS_PKL: /net/eichler/vol2/eee_shared/assemblies/hg38/indexes/hg38_noM/DTS_windows/hg38_sunk_slide/500_bp_windows.sunks.pkl
        CONTROL_LOCATIONS: /net/eichler/vol2/eee_shared/assemblies/hg38/read_depth/illumina/control_location_hg38
        GENOME: /net/eichler/vol2/eee_shared/assemblies/hg38/indexes/hg38_noM/mrsfastULTRA/hg38.rmsk_and_trf.canonical.fa
        DGV_ANNOTATIONS: /net/eichler/vol2/eee_shared/assemblies/hg38/read_depth/illumina/DGV_variation_hg38.annotation.DTS
        GENOMIC_SUPER_DUP_ANNOTATIONS: /net/eichler/vol2/eee_shared/assemblies/hg38/read_depth/illumina/genomicSuperDups_hg38.annotation.DTS
        GAP_ANNOTATIONS: /net/eichler/vol2/eee_shared/assemblies/hg38/read_depth/illumina/genomic_gaps_hg38.annotation.DTS

