---
dts_dir: DTS_files/500_bp_slide
dts_ref_dir: DTS_ref_files/500_bp_slide
gglob_dir: gglob

p_cutoff: 0.0001
cutoff_scale: 3000
wnd_size: 500
max_merge_dif: 0.27

reference: hg38_noM

hg19:
    wnd_contigs: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/500_bp_windows.pkl.contigs
    gaps: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/gap.bed.gz
    dup_tabix: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/superdups.merged.bed.gz
    gene_tabix: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/refGene.txt_sorted.gz
    gc_tabix: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/hg19-gc-w200.GC_content.bed_sorted.gz
    superdups: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/superdups.merged.bed.gz
    segdup_gaps: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/SegDups_Gaps_Merged_hg19.bed
    mask_bed: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/HG19-noWM-pad36.bed

hg38:
    wnd_contigs: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/500_bp_windows.pkl.contigs
    gaps: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/gaps.bed.gz
    dup_tabix: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/wgac_merged.tab.gz
    gene_tabix: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/refGene.txt.sort.gz
    gc_tabix: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/gc_content_1kbp_windows.bed.gz
    superdups: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/genomicSuperDup.tab.gz

hg38_noM:
    wnd_contigs: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/500_bp_windows.wssd.pkl.contigs
    gaps: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/gaps.bed.gz
    dup_tabix: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/wgac_merged.tab.gz
    gene_tabix: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/refGene.txt.sort.gz
    gc_tabix: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/gc_content_1kbp_windows.bed.gz
    segdup_gaps: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/segDups_Gaps_merged_hg38.bed
    mask_bed: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/hg38_noWM_pad36.bed
    superdups: /net/eichler/vol27/projects/human_diversity/nobackups/hsiehph/genomicData/EEElab/mrssnake/genomicSuperDup.tab.gz
